### ISSUE TITLE
generic_type: type "source" referenced unknown base type "gr::hier_block2"

### ISSUE THREAD

**Issue by catkira** [Nuand/gr-bladeRF#7]
Hi,
I am using 
GNU Radio 3.10.1.1
Python 3.8.13
latest version of this repo

When I open 
```
gnuradio-companion gr-bladeRF/apps/fm_receiver.grc
```
generating seems to work, but when I hit run I get this error
```
Executing: /usr/bin/python3 -u /mnt/d/git/gr-bladeRF/apps/fm_receiver.py

Traceback (most recent call last):
  File "/mnt/d/git/gr-bladeRF/apps/fm_receiver.py", line 36, in <module>
    import bladeRF
  File "/usr/local/lib/python3.8/dist-packages/bladeRF/__init__.py", line 18, in <module>
    from .bladeRF_python import *
ImportError: generic_type: type "source" referenced unknown base type "gr::hier_block2"
```

**Comment by catkira** [comment]
I dont know if its related, but there is also a block called "Message Pair to Var" that I have to remove before I can generate
<img width="816" alt="gr-bladerf problem" src="https://user-images.githubusercontent.com/13425558/165909584-e07a5026-e524-42c4-84de-18add7ac200a.PNG">

**Comment by catkira** [comment]
I just downgraded to GNU Radio 3.9.5.0, but the error stays the same

**Comment by smusihin** [comment]
Hi, @catkira. This error is often found in gnuradio projects. This is may due to mismatch pybind11 version was used in GnuRadio build and pybind11 in your OS. For example, when I was building gr-bladeRF for RPi, I also built GNURadio. 

https://github.com/Nuand/gr-bladeRF/tree/main/raspberry#3-crossplatform-build-volk-and-gnuradio-using-docker-and-install-on-rpi

Check out pybind11 version.

**Comment by catkira** [comment]
I tried many things, recompiling everything with the same pybind11 or using precompiled binaries for Ubuntu 20.04, but it does not work.

**Comment by catkira** [comment]
after recompiling everything from source it finally works - thats linux :P
